name: Publish PowerShell Module
description: Publishes a PowerShell module to the PowerShell Gallery.
inputs:
  modulePath:
    description: The filesystem path to the module to publish
    required: true
outputs:
  successfullyPublished: # id of output
    description: Whether or not the publish command was successful
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.NuGetApiKey }}
    - ${{ inputs.modulePath }}